<?xml version="1.0" encoding="utf-8"?>

<Database Name="TourDb" Class="TourDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings"
              ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\TourDb.mdf;Integrated Security=True"
              SettingsObjectName="CursProject.Properties.Settings" SettingsPropertyName="TourDbConnectionString"
              Provider="System.Data.SqlClient" />
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="City_Tour" Member="Tours" ThisKey="Id" OtherKey="CityId" Type="Tour" />
      <Association Name="Country_City" Member="Country" ThisKey="CountryId" OtherKey="Id" Type="Country"
                   IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Country_City" Member="Cities" ThisKey="Id" OtherKey="CountryId" Type="City" />
    </Type>
  </Table>
  <Table Name="dbo.Excursion" Member="Excursions">
    <Type Name="Excursion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Excursion_TourExcursion" Member="TourExcursions" ThisKey="Id" OtherKey="ExcursionId"
                   Type="TourExcursion" />
    </Type>
  </Table>
  <Table Name="dbo.Hotel" Member="Hotels">
    <Type Name="Hotel">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Hotel_Trip" Member="Trips" ThisKey="Id" OtherKey="HotelId" Type="Trip" />
    </Type>
  </Table>
  <Table Name="dbo.Meal" Member="Meals">
    <Type Name="Meal">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Meal_Trip" Member="Trips" ThisKey="Id" OtherKey="MealId" Type="Trip" />
    </Type>
  </Table>
  <Table Name="dbo.Tour" Member="Tours">
    <Type Name="Tour">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NameForClients" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tour_TourExcursion" Member="TourExcursions" ThisKey="Id" OtherKey="TourId"
                   Type="TourExcursion" />
      <Association Name="Tour_Trip" Member="Trips" ThisKey="Id" OtherKey="TourId" Type="Trip" />
      <Association Name="City_Tour" Member="City" ThisKey="CityId" OtherKey="Id" Type="City" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TourExcursion" Member="TourExcursions">
    <Type Name="TourExcursion">
      <Column Name="TourId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="ExcursionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Excursion_TourExcursion" Member="Excursion" ThisKey="ExcursionId" OtherKey="Id"
                   Type="Excursion" IsForeignKey="true" />
      <Association Name="Tour_TourExcursion" Member="Tour" ThisKey="TourId" OtherKey="Id" Type="Tour"
                   IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trip" Member="Trips">
    <Type Name="Trip">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="TourId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MealId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransportId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HotelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateDeparture" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateArival" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Nights" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TourPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MealPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransportPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HotelPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Trip_TripClient" Member="TripClients" ThisKey="Id" OtherKey="TripId" Type="TripClient" />
      <Association Name="Hotel_Trip" Member="Hotel" ThisKey="HotelId" OtherKey="Id" Type="Hotel" IsForeignKey="true" />
      <Association Name="Meal_Trip" Member="Meal" ThisKey="MealId" OtherKey="Id" Type="Meal" IsForeignKey="true" />
      <Association Name="Tour_Trip" Member="Tour" ThisKey="TourId" OtherKey="Id" Type="Tour" IsForeignKey="true" />
      <Association Name="Transport_Trip" Member="Transport" ThisKey="TransportId" OtherKey="Id" Type="Transport"
                   IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TripClient" Member="TripClients">
    <Type Name="TripClient">
      <Column Name="TripId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fio" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Trip_TripClient" Member="Trip" ThisKey="TripId" OtherKey="Id" Type="Trip" IsForeignKey="true" />
      <Association Name="Client_TripClient" Member="Client" ThisKey="ClientId" OtherKey="Id" Type="Client"
                   IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transport" Member="Transports">
    <Type Name="Transport">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Transport_Trip" Member="Trips" ThisKey="Id" OtherKey="TransportId" Type="Trip" />
    </Type>
  </Table>
  <Table Name="dbo.Discount" Member="Discounts">
    <Type Name="Discount">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Range" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true"
              CanBeNull="false" />
      <Column Name="Fio" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DocType" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DocData" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Client_TripClient" Member="TripClients" ThisKey="Id" OtherKey="ClientId" Type="TripClient" />
    </Type>
  </Table>
</Database>